# Generated by Django 4.1.7 on 2023-05-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_servico_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(choices=[('AB', 'Alinhamento e Balanceamento'), ('AC', 'Ar Condicionado'), ('DP', 'Diagnostico de Problemas'), ('EM', 'Manutenção/Troca na Embreagem'), ('LB', 'Limpeza de Bico'), ('S', 'Manutenção/Troca na Suspensão'), ('M', 'Manutenção no Motor'), ('SA', 'Manutenção no Sistema de Arrefecimento'), ('F', 'Manutenção/Troca do Freio'), ('SI', 'Sistema de Ignição'), ('SE', 'Sistema de Escape'), ('SEL', 'Serviços Elétricos'), ('ST', 'Serviços de Transmissão'), ('TB', 'Troca de Bateria'), ('TG', 'Garantia Serviço/Troca'), ('TF', 'Troca de Filtros'), ('TO', 'Trocar de oleo'), ('TR', 'Troca do Radiador'), ('TCD', 'Troca da Correia Dentada'), ('TM', 'Troca de Mangueiras'), ('TV', 'Troca das Velas'), ('TP', 'Troca de Pneus'), ('OS', 'Outros Serviços')], max_length=3),
        ),
    ]
