# Generated by Django 4.1.7 on 2023-05-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_categoriamanutencao_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='observacao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
